### ISSUE TITLE
make stopped (linux-libbsd)

### ISSUE THREAD

**Issue by q-pa** [jgrafton/freebsd-obsidian#3]
Hi, 

I am trying to install freebsd-obsidian on GhostBSD 23.10.1, /usr/src is populated but I am running into the following error:

```
sudo ./ob-installer install  
kldstat: can't find file linux_libbsd: No such file or directory
make: no target to make.

make: stopped in /usr/home/qpa/git/freebsd-obsidian-main
make: don't know how to make install. Stop

make: stopped in /usr/home/qpa/git/freebsd-obsidian-main
kldload: can't load linux_libbsd: No such file or directory
...
```
The rest installs fine, but without linux_libbsd I cannot open any vaults.

**Comment by q-pa** [comment]
additional information:

mrclksr's linux-browser-installer is also installed (/compat/ubuntu).

**Comment by q-pa** [comment]
GhostBSD 23.10.1 is based on(?)  FreeBSD 13.2-STABLE GENERIC amd64 1302508 1302508 (info from `freebsd-version -kru ; uname -aKU `)

**Comment by q-pa** [comment]
Sorry for the noise but I found the linux_libbsd.ko in /usr/obj/usr/src/amd64.amd64/sys/modules/linux_libbsd/kmod/ and copied it to /boot/modules. Obsidian works now. 

Since there was an error I leave it up to you to close this as "solved". Thanks for making freebsd-obsidian!

**Comment by q-pa** [comment]
I also tried building this https://github.com/wulf7/linux-libbsd but there was an error, too. Cannot tell which might have produced the kernel module. From the time stamp I tend to believe it was this endeavor:  https://github.com/wulf7/linux-libbsd.

**Comment by antihrn42** [comment]
hi, i'm reading this as i have the same issue (created also an separate issue).
i did not find linux_libbsd.ko in the directory you mentioned, and a locate doesn't give anything so i guess i do not have the module on my computer. do you know how i can install it? nothing in pkg, maybe in ports?

**Comment by jgrafton** [comment]
There was a bug in building libbsd, pull the repo and try the install again.
